inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec

Style/Documentation:
  Enabled: False

Metrics/BlockLength:
  Enabled: False

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/*'

Rspec/ExampleLength:
  Exclude:
    - 'spec/features/*'
