extend_config:
  - .rubocop.yml

ignore:
  - 'storage/**/*'
  - 'db/migrate/2020*.rb'
  - 'db/migrate/2021*.rb'
  - 'db/migrate/2022*.rb'
  - 'db/migrate/2023*.rb'
  - 'db/migrate/202405*.rb'
  - 'db/migrate/202406*.rb'
  - 'lib/tasks/deployment/2020*'
  - 'lib/tasks/deployment/2021*'
  - 'lib/tasks/deployment/2022*'
  - 'lib/tasks/deployment/2023*'
