language: ruby
rvm:
  - 2.7.0
  - latest
services:
  - postgresql
jobs:
  include:
    - stage: test
      script: rspec
      # - stage: seed data
      #   script: rake db:create db:migrate db:seed
