name: docker

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - 'bin/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - 'bin/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome-debug
      volumes:
        - ${{ github.workspace }}/tmp/downloads:/home/seluser/Downloads
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Build
        run: docker-compose build
      - name: bundle install
        run: docker-compose run web bundle install
      - name: db:reset
        run: docker-compose run web rails db:reset
      - name: docker UP
        run: docker-compose up -d
      - name: Test
        run: docker-compose exec -T web bundle exec rspec spec
