name: ERB lint

on:
  - pull_request_target

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1

    - name: install gem erb_lint
      run: |
        gem install erb_lint

    - name: ERB lint
      run: erblint --lint-all --autocorrect
