on:
  push:
    branches:
      - main
    paths-ignore:
      - "doc/**"
      - "**/*.md"
      - "bin/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "doc/**"
      - "**/*.md"
      - "bin/**"

jobs:
  rake-after_party:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run rake after_party
        run: rake after_party:run
